version: '2'

services:
  postgres:
    image: postgres:9.6

  api:
    restart: always
    image: local-api
    build:
      context: .
      dockerfile: ./api/compose/local/Dockerfile
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./api/:/code
    env_file:
      - ./api/.env.local
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  documentation:
    restart: always
    image: documentation
    build:
      context: .
      dockerfile: ./documentation/Dockerfile
    command: "mkdocs serve"
    volumes:
      - ./documentation:/code
    ports:
      - "8001:8001"

  frontend:
    restart: always
    image: local-frontend
    build:
      context: .
      dockerfile: ./frontend/compose/local/Dockerfile
    command: "npm run dev"
    volumes:
      - ./frontend:/code
      - ./frontend/node_modules:/code/node_modules
    ports:
      - "8080:8080"