version: '2'

services:
  postgres:
    image: postgres:9.6

  api:
    restart: always
    image: local-api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./api/:/code
    env_file:
      - ./api/.env/.local
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  documentation:
    restart: always
    image: documentation
    build:
      context: .
      dockerfile: ./documentation/Dockerfile
    command: "mkdocs serve"
    volumes:
      - ./documentation:/code
    ports:
      - "8001:8001"
