site_name: standup
site_description: A team mangement tool for managers without time,
repo_url: https://github.com/adoval4/standup
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/adoval4">adoval4</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
