# Generated by Django 2.1.11 on 2019-11-25 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191125_0056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'get_latest_by': 'created', 'ordering': ['created', '-modified']},
        ),
    ]
