# Generated by Django 2.1.11 on 2019-12-04 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191125_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified']},
        ),
    ]
